version: '3.4'

services:
  database:
    image: "mcr.microsoft.com/mssql/server"
  mediator-pattern-demo:
    image: ${DOCKER_REGISTRY-}mediatorpatterndemo
    build:
      context: .
      dockerfile: mediator-pattern-demo/Dockerfile
