version: '3.4'

services:
  database:
    environment:
        SA_PASSWORD: "DatabasePassw0rd123"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  mediator-pattern-demo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44339
    ports:
      - "59327:80"
      - "44339:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro