version: '3.4'

services:
  database:
    environment:
        SA_PASSWORD: "DatabasePassw0rd123"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  demo.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44340
    ports:
      - "59328:80"
      - "44340:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro